version = 1

[services.goku]
command = "bun ~/src/ts/daemons/goku-watch.ts"

[install]
eza.pkg-path = "eza"
bat.pkg-path = "bat"
edgedb.pkg-path = "edgedb"
python3.pkg-path = "python3"
coreutils.pkg-path = "coreutils"
parallel.pkg-path = "parallel"
nil.pkg-path = "nil"
nixfmt.pkg-path = "nixfmt"
nixd.pkg-path = "nixd"
deploy-rs.pkg-path = "deploy-rs"
nixos-rebuild.pkg-path = "nixos-rebuild"
nix-index.pkg-path = "nix-index"
go_1_23.pkg-path = "go_1_23"
gh.pkg-path = "gh"
xcpretty.pkg-path = "xcpretty"
htop.pkg-path = "htop"
lsof.pkg-path = "lsof"
fd.pkg-path = "fd"
topgrade.pkg-path = "topgrade"
mkpasswd.pkg-path = "mkpasswd"
poetry.pkg-path = "poetry"
hyperfine.pkg-path = "hyperfine"

# TODO: see if https://floxcommunitygroup.slack.com/archives/C06NYALM8P8/p1731846414514329 it can just be
# systems = ["aarch64-darwin"]
[options]
systems = ["aarch64-darwin", "aarch64-linux", "x86_64-darwin", "x86_64-linux"]
cuda-detection = false
